### ISSUE TITLE
Code update

### ISSUE THREAD

**Issue by mb-Ma** [ChengqingYu/GinAR#1]
Hi Chengqing,

Congratulations for accepted by KDD'24.

Could you let me know when you're going to open the code?

**Comment by ChengqingYu** [comment]
Thank you for your attention. The related review is expected to be completed by late June. Besides,  since I am currently preparing for the defense of my doctoral proposal report,  I will try my best to organize and upload the code in July after completing these matters.

**Comment by mb-Ma** [comment]
Thanks for your response.

Good luck.

---- Replied Message ----
| From | Chengqing ***@***.***> |
| Date | 05/24/2024 18:04 |
| To | ChengqingYu/GinAR ***@***.***> |
| Cc | Minbo ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ChengqingYu/GinAR] Code update (Issue #1) |

Thank you for your attention. The related review is expected to be completed by late June. Besides, since I am currently preparing for the defense of my doctoral proposal report, I will try my best to organize and upload the code in July after completing these matters.
